from .sloanviewer.sloanviewer import SloanViewer
from .standardcandles.standardcandles import StandardCandles
from .cosmos.cosmos import Cosmos
from .cubedemo import CubeDemo
from .shipdemo import ShipDemo
from .cmbrdemo import CMBRDemo
from .earthdemo import EarthDemo
from .globesdemo import GlobesDemo
from .kartracer.kartracer import KartRacer
